#!/bin/sh

# Use neovim for vim if present
[ -x "$command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
  alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want
alias \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -vI" \
  bc="bc -ql" \
  mkd="mkdir -pv" \
  xevs="xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf \"%-3s %s\\n\", \$5, \$8 }'"

# Colorize commands when possible
alias \
  grep="grep --color=auto" \
  diff="diff --color=auto" \
  cat="bat"

# Alias for trashcan-cli
alias \
  t="trash-put" \
  te="trash-empty" \
  tl="trash-list" \
  tre="trash-restore" \
  trm="trash-rm"


# Alias replacing ls
alias ls="exa -al --color=always --group-directories-first" \ # list
alias la="exa -a --color=always --group-directories-first" \  # all files and dirs
alias ll="exa -l --color=always --group-directories-first" \  # long format
alias lt="exa -aT --color=always --group-directories-first" \ # tree listing

# Making long commands shorter
alias \
  ka="killall" \
  g="git" \
  trem="transmission-remote" \
  sdn="shutdown -h now" \
  c="code" \
  v="$EDITOR" \
  p="pacman" \
  z="zathura" \
  evi="evince"

# script alias
alias \
lf="lfub" \
